spring:
  thymeleaf:
    cache: false
application:
  api:
    retry:
      limit: 10
logging:
  level:
    org:
      springframework:
        web:
          client: info
      apache:
        http:
          wire: debug
